server:
    port: 9000

#Swagger Settings
# http://서버주소/swagger-ui.html
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html

spring:
    #DataBase Settings
    dataSource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sbank?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: root #아직 미정(local에서 진행시 각자에게 맞는 포트번호와 아이디 비번으로 변경 후 돌리시면 됩니다!)
        password: root #아직 미정
    
    sql:
        init:
            mode: always

    #JPA Settings
    jpa:
        open-in-view: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
        generate-ddl: false
        show-sql: true
        database: mysql
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true

    # Kakao Settings
    # security:
    #     oauth2:
    #         client:
    #             registration:
    #                 kakao:
    #                     client-id: #cliendId key
    #                     client-secret: #clientSecret key
    #                     redirect-uri:  https://dapi.kakao.com/v2/vision/face/detect #얼굴인식

#JWT Settings
jwt:
    header: Authorization
    secret: c3NhZnktZ3VtaS10d28tYmFuLWQyMDEtYmFja2VuZC1qd3Qtc2VjcmV0LXNzYWZ5LWd1bWktdHdvLWJhbi1kMjAxLWJhY2tlbmQtand0LXNlY3JldAo= #jwt secret key
    #echo 'ssafy-gumi-two-ban-d201-backend-jwt-secret-ssafy-gumi-two-ban-d201-backend-jwt-secret'|base64

# Hibernate logging
logging:
    level:
        org:
            hibernate:
                sql: Debug
                type:
                    descriptor:
                        sql: trace
